# Generated by Django 4.2.16 on 2024-10-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_employees',
            field=models.PositiveIntegerField(),
        ),
    ]
