# Generated by Django 4.2.16 on 2025-01-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_address',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='hr_name',
            new_name='job_industry',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='industry',
            new_name='linkedin_profile',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='number_of_employees',
            new_name='number_applicants',
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='present_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='province',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
