# Generated by Django 4.2.16 on 2025-01-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_rename_company_address_company_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='barangay',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
