import localFont from "next/font/local";
import "./styles/globals.css";


const geistSans = localFont({
  src: './assets/fonts/GeistVF.woff',  
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: './assets/fonts/GeistMonoVF.woff',  
  variable: "--font-geist-mono",
  weight: "100 900",
});

// For search engine
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="favicon.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
