# Generated by Django 4.2.16 on 2024-10-02 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_initial'),
        ('applicant', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobHiring',
            fields=[
                ('job_hiring_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_industry', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=100)),
                ('work_location', models.CharField(max_length=100)),
                ('work_arrangement', models.CharField(choices=[('Onsite', 'Onsite'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=20)),
                ('num_positions', models.IntegerField()),
                ('job_description', models.TextField()),
                ('qualifications', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('verification_option', models.CharField(max_length=50)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('application_deadline', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Closed', 'Closed')], max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_name', models.CharField(max_length=100)),
                ('weight_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preference', models.CharField(blank=True, max_length=255, null=True)),
                ('job_hiring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_criteria', to='job.jobhiring')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('educational_documents', models.FileField(blank=True, null=True, upload_to='education_docs/')),
                ('experience_documents', models.FileField(blank=True, null=True, upload_to='experience_docs/')),
                ('additional_documents', models.FileField(blank=True, null=True, upload_to='additional_docs/')),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Scheduled Interview', 'Scheduled Interview'), ('Accepted', 'Accepted'), ('Withdrawn', 'Withdrawn')], max_length=20)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('interview_location', models.CharField(blank=True, max_length=255, null=True)),
                ('scores', models.CharField(max_length=255)),
                ('verification_result', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
                ('job_hiring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobhiring')),
            ],
        ),
    ]
