# Generated by Django 4.2.16 on 2024-10-22 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0003_alter_applicant_contact_number'),
        ('company', '0003_alter_company_company_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobHiring',
            fields=[
                ('job_hiring_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_industry', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=100)),
                ('work_location', models.CharField(max_length=100)),
                ('work_setup', models.CharField(choices=[('Onsite', 'Onsite'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=20)),
                ('num_positions', models.PositiveIntegerField()),
                ('job_description', models.TextField()),
                ('experience_level', models.CharField(choices=[('Internship', 'Internship'), ('Entry-level', 'Entry-level'), ('Associate', 'Associate'), ('Mid-level', 'Mid-level'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Manager', 'Manager')], max_length=20)),
                ('qualifications', models.CharField(max_length=300)),
                ('salary', models.PositiveIntegerField()),
                ('benefits', models.CharField(max_length=300)),
                ('verification_option', models.CharField(max_length=300)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('application_deadline', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Active', 'Active'), ('Closed', 'Closed')], max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_name', models.CharField(max_length=100)),
                ('weight_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preference', models.CharField(blank=True, max_length=255, null=True)),
                ('job_hiring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_criteria', to='jobs.jobhiring')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('job_application_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('educational_documents', models.FileField(blank=True, null=True, upload_to='education_docs/')),
                ('experience_documents', models.FileField(blank=True, null=True, upload_to='experience_docs/')),
                ('additional_documents', models.FileField(blank=True, null=True, upload_to='additional_docs/')),
                ('application_date', models.DateField(auto_now_add=True)),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], max_length=20)),
                ('scores', models.JSONField(blank=True, null=True)),
                ('verification_result', models.JSONField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
                ('job_hiring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobhiring')),
            ],
        ),
    ]
