# Generated by Django 4.2.16 on 2024-11-01 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_applicant_saved_jobs_alter_applicant_contact_number'),
        ('jobs', '0002_delete_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhiring',
            name='schedule',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='salary',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='verification_option',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='scoringcriteria',
            name='criteria_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scoringcriteria',
            name='weight_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('job_application_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('educational_documents', models.FileField(blank=True, null=True, upload_to='education_docs/')),
                ('experience_documents', models.FileField(blank=True, null=True, upload_to='experience_docs/')),
                ('additional_documents', models.FileField(blank=True, null=True, upload_to='additional_docs/')),
                ('application_date', models.DateField(auto_now_add=True)),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], max_length=20)),
                ('scores', models.JSONField(blank=True, null=True)),
                ('verification_result', models.JSONField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
                ('job_hiring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobhiring')),
            ],
        ),
    ]
