# Generated by Django 4.2.16 on 2024-11-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobhiring_schedule_alter_jobhiring_salary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoringcriteria',
            old_name='preference',
            new_name='preference1',
        ),
        migrations.AddField(
            model_name='jobhiring',
            name='frequency',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Semi-Monthly', 'Semi-Monthly'), ('Monthly', 'Monthly'), ('Annual', 'Annual'), ('Daily', 'Daily')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobhiring',
            name='note',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='jobhiring',
            name='required_documents',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='scoringcriteria',
            name='preference2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scoringcriteria',
            name='preference3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='benefits',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='employment_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='experience_level',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Entry-level', 'Entry-level'), ('Associate', 'Associate'), ('Mid-level', 'Mid-level'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Manager', 'Manager')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='job_industry',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='qualifications',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Active', 'Active'), ('Closed', 'Closed')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='verification_option',
            field=models.CharField(choices=[('Score Unverified Credential Fully', 'Score Unverified Credential Fully'), ('Score Unverified Credential 50%', 'Score Unverified Credential 50%'), ('Ignore Unverified Credentials', 'Ignore Unverified Credentials')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='work_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='work_setup',
            field=models.CharField(choices=[('Onsite', 'Onsite'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=20, null=True),
        ),
    ]
