# Generated by Django 4.2.16 on 2024-11-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_preference_scoringcriteria_preference1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoringcriteria',
            old_name='preference1',
            new_name='preference',
        ),
        migrations.RemoveField(
            model_name='scoringcriteria',
            name='preference2',
        ),
        migrations.RemoveField(
            model_name='scoringcriteria',
            name='preference3',
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='qualifications',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='required_documents',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='salary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
