# Generated by Django 4.2.16 on 2024-11-07 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_preference1_scoringcriteria_preference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobhiring',
            old_name='note',
            new_name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='additional_documents',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='educational_documents',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='experience_documents',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applicant_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='benefits',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='employment_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='experience_level',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Entry-level', 'Entry-level'), ('Associate', 'Associate'), ('Mid-level', 'Mid-level'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Manager', 'Manager')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='frequency',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Semi-Monthly', 'Semi-Monthly'), ('Monthly', 'Monthly'), ('Annual', 'Annual'), ('Daily', 'Daily')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='required_documents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='salary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='work_location',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='work_setup',
            field=models.CharField(choices=[('Onsite', 'Onsite'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='scoringcriteria',
            name='preference',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='JobApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Resume', 'Resume'), ('Educational Document', 'Educational Document'), ('Work Experience Document', 'Work Experience Document'), ('Certification Document', 'Certificatione Document'), ('Additional Document', 'Additional Document')], max_length=300)),
                ('document_file', models.FileField(upload_to='job_application_documents/')),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='jobs.jobapplication')),
            ],
        ),
    ]
