# Generated by Django 4.2.16 on 2024-11-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_rename_note_jobhiring_additional_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applicant_name',
        ),
        migrations.AlterField(
            model_name='jobapplicationdocument',
            name='document_file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='jobapplicationdocument',
            name='document_type',
            field=models.CharField(max_length=255),
        ),
    ]
