# Generated by Django 4.2.16 on 2024-12-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobapplication_application_status_recentsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='verification_result',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(max_length=20),
        ),
    ]
