# Generated by Django 4.2.16 on 2025-01-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobapplication_application_status_recentsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='employment_type',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='experience_level',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='frequency',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='verification_option',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='work_setup',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
