# Generated by Django 4.2.16 on 2025-03-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_jobapplication_application_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobhiring',
            old_name='frequency',
            new_name='salary_frequency',
        ),
        migrations.RemoveField(
            model_name='jobhiring',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='jobhiring',
            name='work_location',
        ),
        migrations.AddField(
            model_name='jobhiring',
            name='city',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='jobhiring',
            name='province',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='jobhiring',
            name='region',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='jobhiring',
            name='salaryMax',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='jobhiring',
            name='salaryMin',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='benefits',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
