# Generated by Django 4.2.16 on 2024-12-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_jobapplication_scores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(default='draft', max_length=20),
        ),
    ]
