# Generated by Django 4.2.16 on 2025-03-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_rename_frequency_jobhiring_salary_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhiring',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='verification_option',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
