# Generated by Django 4.2.16 on 2025-03-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_jobhiring_application_deadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobhiring',
            old_name='salaryMax',
            new_name='salary_max',
        ),
        migrations.RenameField(
            model_name='jobhiring',
            old_name='salaryMin',
            new_name='salary_min',
        ),
    ]
