# Generated by Django 4.2.16 on 2025-03-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_rename_salarymax_jobhiring_salary_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhiring',
            name='specialization',
            field=models.JSONField(null=True),
        ),
    ]
