# Generated by Django 4.2.16 on 2025-03-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_jobhiring_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhiring',
            name='city',
            field=models.JSONField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='province',
            field=models.JSONField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='region',
            field=models.JSONField(max_length=300, null=True),
        ),
    ]
