# Generated by Django 4.2.16 on 2025-03-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_jobhiring_city_alter_jobhiring_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhiring',
            name='city',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='province',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='region',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
