# Generated by Django 4.2.16 on 2025-03-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_jobhiring_city_alter_jobhiring_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhiring',
            name='weight_of_criteria',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
