# Generated by Django 4.2.16 on 2025-03-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_jobhiring_weight_of_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobhiring',
            name='additional_notes',
        ),
        migrations.AddField(
            model_name='jobhiring',
            name='additional_points',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
