# Generated by Django 4.2.16 on 2025-04-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_remove_jobhiring_additional_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobhiring',
            name='additional_points',
        ),
        migrations.AddField(
            model_name='jobhiring',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='job_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], max_length=10, null=True),
        ),
    ]
