# Generated by Django 4.2.16 on 2025-04-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_remove_jobhiring_additional_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhiring',
            name='num_applications',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobhiring',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('complete', 'Complete')], max_length=10, null=True),
        ),
    ]
