# Generated by Django 4.2.16 on 2025-04-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_jobhiring_num_applications_alter_jobhiring_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhiring',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
