# Generated by Django 4.2.16 on 2025-04-22 12:31

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_jobhiring_num_applications_alter_jobhiring_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('processed', 'Processed Successfully'), ('error', 'Processing Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplicationdocument',
            name='document_file',
            field=models.FileField(upload_to=jobs.models.get_document_upload_path),
        ),
    ]
