# Generated by Django 4.2.16 on 2025-04-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_alter_jobapplication_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('processed', 'Submitted'), ('error', 'Processing Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
