# Generated by Django 4.2.16 on 2025-04-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
