# Generated by Django 4.2.16 on 2025-04-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_alter_jobapplication_application_status'),
        ('jobs', '0022_alter_jobapplication_application_date'),
    ]

    operations = [
    ]
