# Generated by Django 4.2.16 on 2025-04-27 04:08

from django.db import migrations, models
import google_drive.storage
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_merge_20250427_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='google_drive_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplicationdocument',
            name='document_file',
            field=models.FileField(storage=google_drive.storage.GoogleDriveStorage(), upload_to=jobs.models.get_document_upload_path),
        ),
    ]
