# Generated by Django 4.2.16 on 2025-05-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_merge_20250423_2328'),
        ('jobs', '0024_jobapplicationdocument_google_drive_id_and_more'),
    ]

    operations = [
    ]
