# Generated by Django 4.2.16 on 2025-05-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_merge_20250504_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_location_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='application_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('processed', 'Submitted'), ('error', 'Processing Failed'), ('cancelled', 'Cancelled'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('interview scheduled', 'Interview Scheduled'), ('emailed', 'Emailed'), ('accepted', 'Accepted')], default='draft', max_length=20),
        ),
    ]
