# Generated by Django 4.2.16 on 2025-05-04 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_jobapplication_interview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='job_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication'),
        ),
    ]
