# Generated by Django 4.2.16 on 2025-05-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_jobapplicationdocument_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='folder_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]