# Generated by Django 4.2.16 on 2025-05-06 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_notification_job_application'),
        ('jobs', '0028_jobapplication_folder_url'),
    ]

    operations = [
    ]
