# Generated by Django 4.2.16 on 2025-05-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_merge_20250506_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='folder_url',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('processed', 'Submitted'), ('error', 'Processing Failed'), ('cancelled', 'Cancelled'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('interview scheduled', 'Interview Scheduled'), ('emailed', 'Emailed'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20),
        ),
    ]
