# Generated by Django 4.2.16 on 2025-05-06 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0009_applicant_barangay_applicant_city_and_more'),
        ('jobs', '0030_remove_jobapplication_folder_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applicant.applicant'),
        ),
    ]
