# Generated by Django 4.2.16 on 2024-10-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_jobhiring_num_positions'),
        ('applicant', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='saved_jobs',
            field=models.ManyToManyField(to='job.jobhiring'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='contact_number',
            field=models.PositiveIntegerField(),
        ),
    ]
