# Generated by Django 4.2.16 on 2024-10-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='contact_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
