# Generated by Django 4.2.16 on 2024-11-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_delete_jobapplication'),
        ('applicant', '0003_alter_applicant_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='jobs.jobhiring'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
