# Generated by Django 4.2.16 on 2024-11-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_applicant_saved_jobs_alter_applicant_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='linkedin_profile',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='present_address',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True),
        ),
    ]
