# Generated by Django 4.2.16 on 2024-11-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_alter_applicant_age_alter_applicant_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='contact_number',
            field=models.CharField(null=True),
        ),
    ]
