# Generated by Django 4.2.16 on 2024-11-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0006_alter_applicant_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='first_name',
            new_name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='middle_name',
        ),
    ]
