# Generated by Django 4.2.16 on 2024-12-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_rename_first_name_applicant_applicant_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='applicant_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='postal_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='province',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
