# Generated by Django 4.2.16 on 2024-12-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_rename_applicant_name_applicant_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='barangay',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
